//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class basic_user_role
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public int role_type_id { get; set; }
    
        public virtual basic_users basic_users { get; set; }
        public virtual role_type role_type { get; set; }
    }
}
